In [11]:
## Task 1
import numpy as np
marks = [78, 85, 91, 67, 88] 
data_arr=np.array(marks)
print(df)
print(type(df))
print(df.shape)

[78 85 91 67 88]
<class 'numpy.ndarray'>
(5,)


In [19]:
## Task 3
prices = [120, 450, 780, 220, 560] 
array_one=np.array(prices)
print(df1)
print(df1.ndim)
print(df1.size)


[120 450 780 220 560]
1
5


In [21]:
# prob-4
scores = np.array([85, 92, 78, 90, 88, 76, 95, 89, 84, 91])
print(scores.size)
print(scores.shape)
print(type(scores))
print(scores.ndim)

10
(10,)
<class 'numpy.ndarray'>
1


In [25]:
## Task 4
salary = [25000,30000,45000,28000] 
salary_array= np.array([25000,30000,45000,28000] )
salary_array=df3+5000
for i in range(len(salary)):
    salary[i]=salary[i]+5000
print(df3)
print(salary)

[30000 35000 50000 33000]
[30000, 35000, 50000, 33000]


In [29]:
## Task 5 –     Student Marks Increase 
import numpy as np
marks = [75, 82, 90, 68]
updated_marks_list = [m + 5 for m in marks]
updated_marks_arr = np.array(marks) + 5
print(updated_marks_list)
print(updated_marks_arr)


[80, 87, 95, 73]
[80 87 95 73]


In [1]:
## Task 6
import numpy as np
total_elements = 100000
py_list = list(range(total_elements))
np_array = np.arange(total_elements)


In [3]:
## Task 7
import numpy as np
pr=[20,30,40,50]
npr=np.array([20,30,40,50])
print("list:",pr*2)
print("nparray:",npr*2)

list: [20, 30, 40, 50, 20, 30, 40, 50]
nparray: [ 40  60  80 100]


In [7]:
## Task 8
import numpy as np

stock = [10, 20, 30, 40]
print("Python List:", stock * 2)

npstock = np.array([10, 20, 30, 40])
print("NumPy Array:", npstock* 2)

Python List: [10, 20, 30, 40, 10, 20, 30, 40]
NumPy Array: [20 40 60 80]


In [11]:
## Task 9
expences =[100,200,300,400]
npexp=np.array([100,200,300,400])
print(sum(expences))
print(np.sum(npexp))

1000
1000


In [13]:
## Task 10
marks = np.array([55,65,75,85,95])
print("1st:",marks[0])
print("last :",marks[-1])
print("3st:",marks[2])

1st: 55
last : 95
3st: 75


In [17]:
## Task 11
sales = np.array([120,130,140,150,160,170])
print("First three values:",sales[:3])
print("Last two values:",sales[-2:])
print("Middle values:",sales[2:4])

First three values: [120 130 140]
Last two values: [160 170]
Middle values: [140 150]


In [21]:
## Task 12
mat=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print("first row:",mat[0,:])
print("second column:",mat[:,1])
print("last row:",mat[-1,:])

first row: [1 2 3]
second column: [2 5 8]
last row: [7 8 9]


In [23]:
## Task 13
marks = np.array([35,55,72,89,40,91])
print(marks[marks>=40])

[55 72 89 40 91]


In [25]:
## Task 14
import numpy as np
salaries = np.array([35000, 55000, 45000, 75000, 60000])
print(salaries[salaries > 50000])

[55000 75000 60000]


In [29]:
## Task 15
import numpy as np

temp = np.array([25, 32, 28, 35, 31, 29])

print(temp[temp > 30])

[32 35 31]


In [31]:
## Task 16
ratings = np.array([2,5,4,3,5,1])
print(ratings[[0,2,5]])

[2 4 1]


In [33]:
## Task 17
import numpy as np

books = np.array(["Python", "SQL", "Java", "NumPy", "Pandas"])

print(books[[1, 3, 4]])

['SQL' 'NumPy' 'Pandas']


In [35]:
## Task 18
import numpy as np

scores = np.array([45, 60, 72, 80, 55, 90, 100])

print(scores[[0, 3, 6]])


[ 45  80 100]


In [37]:
## Task 19
import numpy as np
a = np.array([10, 20, 30])
b = np.array([2, 4, 6])
print("Addition:", np.add(a, b))
print("Subtraction:", np.subtract(a, b))
print("Multiplication:", np.multiply(a, b))
print("Division:", np.divide(a, b))

Addition: [12 24 36]
Subtraction: [ 8 16 24]
Multiplication: [ 20  80 180]
Division: [5. 5. 5.]


In [50]:
## Task 20
a = np.array([10, 20, 30])
print(np.sqrt(a))
print(np.square(a))
print(np.exp(a))


[3.16227766 4.47213595 5.47722558]
[100 400 900]
[2.20264658e+04 4.85165195e+08 1.06864746e+13]


In [62]:
## Task 21
import numpy as np
degrees = np.array([0, 30, 45, 60, 90])
radians = np.deg2rad(degrees)
print("Sin:", np.sin(radians))
print("Sin:", np.sin(degrees))
print("cos:", np.cos(radians))
print("cos:", np.cos(degrees))
print("tan:", np.tan(radians))
print("tan:", np.tan(degrees))

Sin: [0.         0.5        0.70710678 0.8660254  1.        ]
Sin: [ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666]
cos: [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
cos: [ 1.          0.15425145  0.52532199 -0.95241298 -0.44807362]
tan: [0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]
tan: [ 0.         -6.4053312   1.61977519  0.32004039 -1.99520041]


In [68]:
## Task 22
marks = np.array([78,85,91,67,88])
print(np.median(marks))
print(np.mean(marks))
print( np.sum(marks))
print(np.min(marks))
print(np.max(marks))

85.0
81.8
409
67
91


In [76]:
## Task 23
prod= np.array([120,150,130,170,160,180])
print(np.std(prod))
print(np.var(prod))
print(np.mean(prod))

21.147629234082533
447.2222222222222
151.66666666666666


In [78]:
## Task 24
sales = np.array([25000,27000,30000,28000,35000])

print("Sum:", np.sum(sales))
print("Mean:", np.mean(sales))
print("Maximum:", np.max(sales))
print("Minimum:", np.min(sales))
print("Standard Deviation:", np.std(sales))
print("Variance:", np.var(sales))

Sum: 145000
Mean: 29000.0
Maximum: 35000
Minimum: 25000
Standard Deviation: 3405.87727318528
Variance: 11600000.0


In [82]:
## Task 25
marks = np.array([78, 85, 91, 67, 88])
print(np.argmax(marks))
print(np.argmin(marks))


2
3


In [84]:
## Task 26
savings = np.array([100,200,300,400])
print(np.cumsum(savings))
print(np.cumprod(savings))

[ 100  300  600 1000]
[        100       20000     6000000 -1894967296]


In [88]:
## Task 27
health = np.array([True,True,False,True])
print(np.all(health))
print(np.any(health))

False
True
